version: '3.8'

services:
  meeting-bot:
    build:
      context: .
      dockerfile: DockerFile
    container_name: meeting-bot

    volumes:
      - .:/app

    group_add:
      - audio

    environment:
      - PULSE_SERVER=unix:/tmp/pulse/native
      - XDG_RUNTIME_DIR=/tmp
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - PYTHONUNBUFFERED=1

    ports:
      - "5000:5000"

    stdin_open: true
    tty: true