"""Added Audio,Meeting model

Revision ID: 2e0eeb8393c3
Revises: beee303f91e0
Create Date: 2026-04-24 17:25:42.935124

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e0eeb8393c3'
down_revision: Union[str, Sequence[str], None] = 'beee303f91e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration to upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create all enum types first
    botstatus_enum = postgresql.ENUM('REGISTERED', 'SCHEDULED', 'WAITING_ROOM', 'DENIED', 'MEETING_JOINED', 'RECORDING_STARTED', 'GRACE_PERIOD', 'MEETING_ENDED', 'COMPLETED', 'CANCELLED', 'FAILED', name='botstatus', create_type=True)
    botstatus_enum.create(op.get_bind(), checkfirst=True)

    meetingplatform_enum = postgresql.ENUM('GOOGLE_MEET', 'MICROSOFT_TEAMS', 'ZOOM', name='meetingplatform', create_type=True)
    meetingplatform_enum.create(op.get_bind(), checkfirst=True)

    storageprovider_enum = postgresql.ENUM('LOCAL', 'S3', 'GCS', 'AZURE_BLOB', name='storageprovider', create_type=True)
    storageprovider_enum.create(op.get_bind(), checkfirst=True)

    audioformat_enum = postgresql.ENUM('MP3', 'WAV', 'OPUS', 'OGG', 'FLAC', 'M4A', name='audioformat', create_type=True)
    audioformat_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('processed_file_path', sa.String(), nullable=False),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('bit_rate', sa.Integer(), nullable=True),
    sa.Column('recording_started_at', sa.DateTime(), nullable=True),
    sa.Column('recording_ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('system_logs')
    op.add_column('meetings', sa.Column('bot_status', sa.Enum('REGISTERED', 'SCHEDULED', 'WAITING_ROOM', 'DENIED', 'MEETING_JOINED', 'RECORDING_STARTED', 'GRACE_PERIOD', 'MEETING_ENDED', 'COMPLETED', 'CANCELLED', 'FAILED', name='botstatus'), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE meetings SET bot_status = 'REGISTERED' WHERE bot_status IS NULL")
    # Make NOT NULL
    op.execute("ALTER TABLE meetings ALTER COLUMN bot_status SET NOT NULL")
    op.add_column('meetings', sa.Column('scheduled_time', sa.DateTime(), nullable=True))
    op.add_column('meetings', sa.Column('waiting_room_entered_at', sa.DateTime(), nullable=True))
    op.add_column('meetings', sa.Column('bot_join_time', sa.DateTime(), nullable=True))
    op.add_column('meetings', sa.Column('bot_leave_time', sa.DateTime(), nullable=True))
    op.add_column('meetings', sa.Column('recurring_meeting_id', sa.String(), nullable=True))
    op.add_column('meetings', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('meetings', sa.Column('error_message', sa.String(), nullable=True))
    # Use raw SQL for PostgreSQL to add USING clause
    op.execute("ALTER TABLE meetings ALTER COLUMN platform TYPE meetingplatform USING platform::meetingplatform")
    op.alter_column('meetings', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('meetings', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('meetings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('meetings_url_key'), 'meetings', type_='unique')
    op.drop_column('meetings', 'status')
    op.add_column('users', sa.Column('bot_alias', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Apply migration to downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bot_alias')
    op.add_column('meetings', sa.Column('status', postgresql.ENUM('REGISTERED', 'SCHEDULED', 'BOT_CREATED', 'IN_WAITING_ROOM', 'MEETING_JOINED', 'RECORDING_STARTED', 'COMPLETED', 'FAILED', name='meetingstatus'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('meetings_url_key'), 'meetings', ['url'], postgresql_nulls_not_distinct=False)
    op.alter_column('meetings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('meetings', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('meetings', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('meetings', 'platform',
               existing_type=sa.Enum('GOOGLE_MEET', 'MICROSOFT_TEAMS', 'ZOOM', name='meetingplatform'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('meetings', 'error_message')
    op.drop_column('meetings', 'retry_count')
    op.drop_column('meetings', 'recurring_meeting_id')
    op.drop_column('meetings', 'bot_leave_time')
    op.drop_column('meetings', 'bot_join_time')
    op.drop_column('meetings', 'waiting_room_entered_at')
    op.drop_column('meetings', 'scheduled_time')
    op.drop_column('meetings', 'bot_status')
    op.create_table('system_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('system_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('system_logs_pkey'))
    )
    op.drop_table('audio')
    # ### end Alembic commands ###
