"""add participant_count

Revision ID: a401bd8e3e2a
Revises: 8398bcfdf997
Create Date: 2026-04-29 13:05:30.202026

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a401bd8e3e2a'
down_revision: Union[str, Sequence[str], None] = '8398bcfdf997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration to upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio', 'storage_provider',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('LOCAL', 'S3', 'GCS', 'AZURE_BLOB', name='storageprovider'),
               existing_nullable=False,
               postgresql_using="storage_provider::storageprovider")
    op.alter_column('audio', 'format',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('MP3', 'WAV', 'OPUS', 'OGG', 'FLAC', 'M4A', name='audioformat'),
               existing_nullable=True,
               postgresql_using="format::audioformat")
    op.add_column('meetings', sa.Column('participant_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Apply migration to downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'participant_count')
    op.alter_column('audio', 'format',
               existing_type=sa.Enum('MP3', 'WAV', 'OPUS', 'OGG', 'FLAC', 'M4A', name='audioformat'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audio', 'storage_provider',
               existing_type=sa.Enum('LOCAL', 'S3', 'GCS', 'AZURE_BLOB', name='storageprovider'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
