"""empty message

Revision ID: 4872086446c5
Revises: 3f7039457703
Create Date: 2026-03-11 22:09:51.352514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4872086446c5'
down_revision = '3f7039457703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('event_types', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('calendar_email', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_secret', sa.String(), nullable=True),
    sa.Column('redirect_uri', sa.String(), nullable=True),
    sa.Column('auto_create_jobs', sa.Boolean(), nullable=False),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('meeting_start_buffer_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('webhook_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhooks')
    # ### end Alembic commands ###
