"""Add error_message column to jobs table

Revision ID: add_error_message_column
Revises: e8250b97fd1f
Create Date: 2026-03-06 11:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_error_message_column'
down_revision = 'e8250b97fd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'error_message')
    # ### end Alembic commands ###
