"""added new fields in usermodel

Revision ID: e01e7c687a79
Revises: 42a3cb8cf5a9
Create Date: 2026-03-05 08:18:24.878435

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e01e7c687a79"
down_revision = "42a3cb8cf5a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("meetings", sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("meetings")

    # ### end Alembic commands ###
